"""Add user_id column to comments table

Revision ID: b63030079590
Revises: b5f3e3036183
Create Date: 2022-03-14 21:53:44.061200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b63030079590'
down_revision = 'b5f3e3036183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column(
        'user_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_comments_users_id', 'comments', 'users', [
                          'user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_comments_users_id', 'comments', type_='foreignkey')
    op.drop_column('comments', 'user_id')
    # ### end Alembic commands ###
